<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\backend\Umbrello.Domain\Umbrello.Domain.csproj" />
    <ProjectReference Include="..\..\src\backend\Umbrello.Contracts\Umbrello.Contracts.csproj" />
    <ProjectReference Include="..\..\src\backend\Umbrello.Application\Umbrello.Application.csproj" />
    <ProjectReference Include="..\..\src\backend\Umbrello.Infrastructure\Umbrello.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\backend\Umbrello.Messaging.RabbitMq\Umbrello.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\backend\Umbrello.Api\Umbrello.Api.csproj" />
  </ItemGroup>

</Project>
