<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbrello.Infrastructure\Umbrello.Infrastructure.csproj" />
    <ProjectReference Include="..\Umbrello.Messaging.RabbitMq\Umbrello.Messaging.RabbitMq.csproj" />
  </ItemGroup>

</Project>
