<Project>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>false</InvariantGlobalization>
	</PropertyGroup>
	
	<!-- Qualidade -->
	<PropertyGroup>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
		<NuGetAudit>true</NuGetAudit>
		<NuGetAuditMode>all</NuGetAuditMode>
	</PropertyGroup>
	
	<!-- Metadados -->
	<PropertyGroup>
		<Product>Umbrello</Product>
		<Authors>Luis Paulo</Authors>
		<RepositoryUrl>https://github.com/luis-paulo-tdo/umbrello</RepositoryUrl>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	
</Project>