<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Umbrello.Scheduler-64798d07-2773-4581-aea0-ba15ba44ec50</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbrello.Infrastructure\Umbrello.Infrastructure.csproj" />
    <ProjectReference Include="..\Umbrello.Messaging.RabbitMq\Umbrello.Messaging.RabbitMq.csproj" />
  </ItemGroup>
</Project>
