<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-Umbrello.Worker.Notifications-f01cef5c-e346-41ac-9e00-8c9ff9dd8807</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbrello.Infrastructure\Umbrello.Infrastructure.csproj" />
    <ProjectReference Include="..\Umbrello.Messaging.RabbitMq\Umbrello.Messaging.RabbitMq.csproj" />
  </ItemGroup>
</Project>
